### ISSUE TITLE
kobodl.json created like a folder

### ISSUE THREAD

**Issue by crozo5** [subdavis/kobo-book-downloader#10]
When I run the docker /.config with name kobodl.json

Error: Invalid value for '--config': File '/home/kobodl.json' is a directory.

What am I doing wrong?

**Comment by subdavis** [comment]
@crozo5 please paste your full docker command here.  Looks like you somehow created a directory named `kobodl.json`.  This can happen when you put an extra trailing slash in the volume mount.

## Good

`-v ${HOME}/.config/kobodl.json:/home/kobodl.json`

## Bad

`-v ${HOME}/.config/kobodl.json/:/home/kobodl.json`

**Comment by subdavis** [comment]
Docker run command updated.  You may have to remove the old folders that were created.

```
rmdir ~/.config/kobodl.json
rmdir kobo_downloads
```

**Comment by crozo5** [comment]
I use that:

docker run -d \  
--user 0:0 \
--name=kobodl \
-p 5000:5000 \
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/config/kobodl.json:/home/kobodl.json \
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/download:/home/downloads \
subdavis/kobodl \
serve \
--host 0.0.0.0 \
--output-dir /home/downloads

**Comment by subdavis** [comment]
@crozo5 then in your case, the correct docker command will be:

```bash
docker run -d
--name=kobodl
-p 5000:5000
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/config:/home/config
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/download:/home/downloads
subdavis/kobodl
--config /home/config/kobodl.json
serve
--host 0.0.0.0
--output-dir /home/downloads
```

You don't need `--user` if you're running as root.

**Comment by crozo5** [comment]
> @crozo5 then in your case, the correct docker command will be:
> 
> ```shell
> docker run -d \
> --name=kobodl \
> -p 5000:5000 \
> -v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/config:/home/config \
> -v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/download:/home/downloads \
> subdavis/kobodl \
> --config /home/config/kobodl.json \
> serve \
> --host 0.0.0.0 \
> --output-dir /home/downloads
> ```
> 
> You don't need `--user` if you're running as root.

If I use your code, the Kobodl folder is created and inside the confi and downloads folders are created, but nothing else. The kbodl.json file is not created.

**Comment by subdavis** [comment]
> The kbodl.json file is not created.

The kobodl.json file will not be created until you actually go through a login.  Does the HTTP server run?  Are you able to log in?

**Comment by crozo5** [comment]
> > The kbodl.json file is not created.
> 
> The kobodl.json file will not be created until you actually go through a login. Does the HTTP server run? Are you able to log in?

I can't acces to the HTTP server

**Comment by subdavis** [comment]
...logs?

**Comment by crozo5** [comment]
Logs:
 * Serving Flask app "kobodl.app" (lazy loading),
 * Environment: production,
   WARNING: This is a development server. Do not use it in a production deployment.,
   Use a production WSGI server instead.,
 * Debug mode: off,
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit),

I change the port 5000 to port 5050 because I'm using the port 5000 for another thing:
```
docker run -d \
--name=kobodl \
-p 5050:5050 \
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/config:/home/config \
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/download:/home/downloads \
subdavis/kobodl \
--config /home/config/kobodl.json \
serve \
--host 0.0.0.0 \
--output-dir /home/downloads
```

when I acces to http://IP_NAS:5050, ERROR CONNECTION

**Comment by subdavis** [comment]
That isn't how docker works.  You have to map a host port to a container port. 
https://docs.docker.com/config/containers/container-networking/

`-p 5050:5000` maps 5050 to 5000 internally.

If you want the server to listen on 5050, you can pass `serve --port 5050`

**Comment by crozo5** [comment]
> That isn't how docker works. You have to map a host port to a container port.
> https://docs.docker.com/config/containers/container-networking/
> 
> `-p 5050:5000` maps 5050 to 5000 internally.
> 
> If you want the server to listen on 5050, you can pass `serve --port 5050` alongside the --host argument

Works! Thanks!
That's the correct code for me:
```
docker run -d \
--name=kobodl \
-p 5050:5000 \
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/config:/home/config \
-v /share/CACHEDEV3_DATA/DockerVolumes/Kobodl/download:/home/downloads \
subdavis/kobodl \
--config /home/config/kobodl.json \
serve \
--host 0.0.0.0 \
--output-dir /home/downloads
```

**Comment by crozo5** [comment]
Last question and sorry...
Can I download audiobooks with the docker installation? 

I have been able to download audiobooks from my macbook with pypi installation and CLI, but in docker no file has been downloaded to my nas. How should I do it?

**Comment by subdavis** [comment]
Not yet.  You'll need to use the command line tools.
