### ISSUE TITLE
KoboDL not adding users

### ISSUE THREAD

**Issue by chrisdma** [subdavis/kobo-book-downloader#101]
**Describe the issue**
kobodl, both python and windows binaries, are not adding my user to the user list

**To Reproduce**
1. Download kobodl for windows
2. Run kobodl user add
3. enter email
4. enter password
5. Copy captcha code and hit enter at waiting prompt
6. kobodl gets stuck at the add prompt and only shows the captcha code

**Expected behavior**
Expect the program to add the user account

**Screenshots**
![NVIDIA_Share_qj8Js8qf53](https://user-images.githubusercontent.com/43798323/230997657-f1b51c79-2ddf-4248-a9b7-4d8ffe7aae49.png)

**Desktop (please complete the following information):**
 - OS: Windows
-  Install method and python version: python and windows binary
 - Kobodl Version 0.9.3

**Additional context**

**Comment by subdavis** [comment]
Are you using a kobo account or some other identity provider?

> NOTE: You must have a kobo email login for this tool to work (you can't use an external provider like Google or Facebook). However, you can create a NEW kobo account and link it with your existing account on the user profile page. Go to My Account -> Account Settings to link your new kobo login.

**Comment by chrisdma** [comment]
Any idea on how to fix the login issue?

**Comment by subdavis** [comment]
I appreciate the detailed bug report.  This has happened for various people over the years, and its usually because of what I said above.  Sounds like that isn't the issue for you.

I don't really know off the top of my head what you can try, aside from using the Calibre plugins I mention at the top of the README as an alternative to kobodl.

**Comment by chrisdma** [comment]
> I appreciate the detailed bug report. This has happened for various people over the years, and its usually because of what I said above. Sounds like that isn't the issue for you. I have never been able to reproduce myself.
> 
> I don't really know off the top of my head what you can try, aside from using the Calibre plugins I mention at the top of the README as an alternative to kobodl.

That didn't work either; Obok is showing the book as DRM-free which is why I wanted to try this. Thanks anyways.

**Comment by chrisdma** [comment]
@subdavis What about a way for me to manually get the access token/cookie from an active login session and pass it to the app/script?

**Comment by chrisdma** [comment]
Would you actually be able to give me a sample json config file? I managed to get a login working from kobo-book-downloader (even though I couldn't get the downloader working) that has the AccessToken, DeviceId, RefreshToken, UserId, and UserKey properties. Can I make this usable with kobodl?

**Comment by chrisdma** [comment]
This worked, awesome! Thank you mate!

**Comment by mslmn** [comment]
When I try specifying the json path it still hangs after pasting the captcha response. Any help? I'm on an M1 mac.

**Comment by chrisdma** [comment]
> When I try specifying the json path it still hangs after pasting the captcha response. Any help? I'm on an M1 mac.

Do what I did and use kobo-book-downloader to generate  your json authorization and use those values to build a json for this project and itll work.

**Comment by mslmn** [comment]
How do I do this?

**Comment by chrisdma** [comment]
By downloading kobo-book-downloader and using it to get the config thats generated; basically what I said in my last message lol

**Comment by mslmn** [comment]
How do I get the generated config? Where is it located?
