### ISSUE TITLE
Kobo changed something again

### ISSUE THREAD

**Issue by spectdecomp** [subdavis/kobo-book-downloader#109]
**Describe the issue**
kobodl pre-built binary is not adding users to user list

**To Reproduce**
1. Download kobodl for Linux
2. Run "kobodl user add"
3. Enter email and password
4. Follow the description and obtain captcha code
5. Kobo refuses to log in

**Expected behavior**
Add users to the user list without hindrance

**Screenshots**
![kobodl_issue](https://github.com/subdavis/kobo-book-downloader/assets/59621210/8541b019-b587-4515-8baa-c6edd9149369)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 -  Install method and python version: pre-bulit binary, python 3.11.7
 - Kobodl Version 0.9.3

**Additional context**
I saved the contents of loginpage_error.html to pastebin
[loginpage_error](https://paaster.io/mQa__y9rpaT_hy8miLels#OVSXdG3HiE-tAxg8zbsshm58j4HkVtx3oYETTHydExY)

**Comment by AudioAnchorite** [comment]
I just started using this depot today and I have no issues logging in yet...

**Comment by Abstra208** [comment]
@spectdecomp This error happened because you did not enter the correct login info, make sure your account has a Rakuten login method. If you are still having a problem, reply to this issue.

**Comment by spectdecomp** [comment]
> @spectdecomp This error happened because you did not enter the correct login info, make sure your account has a Rakuten login method. If you are still having a problem, reply to this issue.

Thank you. It was necessary to be able to log in not only with Rakuten Kobo account but also with Rakuten ID. Set this issue to Close.

![Issue_Solved](https://github.com/user-attachments/assets/a52987c9-8bb0-4041-a228-f724012b135a)
