### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by aa545** [subdavis/kobo-book-downloader#127]
![Screenshot 2024-11-18 203608](https://github.com/user-attachments/assets/11ee53a2-a2c3-4ad9-a6ee-76e77c29e9ef)
is there a solution to this error? i got it when i tried to add a user

**Comment by rrcollier** [comment]
I'm seeing this error from the cli, after I'm unable to get a recaptcha to show up on the kobo site to give me a token
