### ISSUE TITLE
Download error for a book that isn't in my list

### ISSUE THREAD

**Issue by jlangeveld** [subdavis/kobo-book-downloader#14]
kobodl book get --get-all fails with << kobodl.kobo.KoboException: Download URL list is empty for product '...' >>, but when I run

kobodl book list

There isn't any book with the mentioned id...

What can I do to find out which book is failing?

**Comment by subdavis** [comment]
Looks like archived books aren't getting processed correctly.  You appear to have at least one achrived book on your Kobo account.  I'll take a look

**Comment by subdavis** [comment]
In the mean time, you can pass the `--read` to the list command to see the hidden book

**Comment by subdavis** [comment]
I actually can't figure out what's going on.  Even though the book may be hidden for you in the list, it should also be skipped correctly during `get --get-all`.

Please try the following:

1. `kobodl book list --read` and see if any new material appears.
2. If it does, try to download it `kobodl  book get <id>`

What error does that throw?  Thanks for the bug report.  Obviously even if `--get-all` isn't working, you can still download books one at a time, right?

**Comment by jlangeveld** [comment]
I changed the code to print the book to download before downloading it, I sent a PR.

When I check the bookMeta for the troublesome book, I see DownloadURLs in the meta, all of them are DRM except for some samples.

The call to content_access_book however returns empty lists:
{'ContentUrls': [], 'ContentKeys': []}                                                                                                                                                                                                         

Downloading using book get <id> gives the same problem.

I worked around it by manually downloading the book from the kobo site and writing the file using the correct name if the kobo_downloads/ directory - which forces --get-all to skip the book...

**Comment by Nosgoroth** [comment]
This happens when you have preorders too, which naturally don't have a download URL. Shouldn't `get --get-all`  at least handle the error gracefully instead of dying when it encounters a preorder?

I can see the preordered book using `kobodl book list --read`, by the way.
