### ISSUE TITLE
Investigate audiobook decryption failure issue

### ISSUE THREAD

**Issue by stylishworker** [subdavis/kobo-book-downloader#17]
Hi I ran into this error during install but it finished anyway, I logged in but the downloaded audiobook was <1mb all incomplete files could this be the reason?
[Failed building wheel for stringcase.txt](https://github.com/subdavis/kobo-book-downloader/files/4742249/Failed.building.wheel.for.stringcase.txt)

Building wheels for collected packages: stringcase
  Running setup.py bdist_wheel for stringcase ... error
  Complete output from command /home/zen/my_env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z77z3eb_/stringcase/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpjr1ch53vpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for stringcase
  Running setup.py clean for stringcase
Failed to build stringcase

**Comment by subdavis** [comment]
What platform, what python version?

**Comment by stylishworker** [comment]
There's good news and bad news

Good news you were right updating to python 3.7 and installing wheel solved
fixed the installation error

Bad news it seems that wasn't the reason that the book was corrupt even
with proper install the book is still coming out <1 MB
https://send.firefox.com/download/3dd0dd44aa2ffa10/#EnQ-ffwgl2ABiM9ciaHR6Q
strangely these files are .m4a my previous downloads were .mp3 could this
be the reason?

**Comment by subdavis** [comment]
It's probably an unsupported encryption type. Some audiobooks simply aren't able to be decrypted, unfortunately.

It would be useful to know which book this is, I may buy it to see what's wrong :/

**Comment by stylishworker** [comment]
ooh I had actually attached the corrupt download on the firefox send link.
Anyhow, the title is: Peace Is Every Step The Path of Mindfulness in
Everyday Life by Thich Nhat Hanh
https://www.kobo.com/us/en/audiobook/peace-is-every-step-2

**Comment by subdavis** [comment]
I haven't been able to reproduce this with other audiobooks and I'm not going to spend the $14 on this one to debug it.

Someone else will have to spend the time to sort this out if they want.  I don't use audiobooks, the feature was added by a contributor.
