### ISSUE TITLE
Suggestion: Have an option to pass cookies to sign on

### ISSUE THREAD

**Issue by TAbdiukov** [subdavis/kobo-book-downloader#18]
I suggest having an option to pass cookies to sign on. Advantages:

* Simpler - no captcha trickery, quick 
* Safer
* Less complexity

What do you think?

**Comment by subdavis** [comment]
I don’t know if we’re on the same page yet. Are you aware of how this tool mimics an Android app?  See the bottom of the readme.  Kobo does not provide access to purchased materials except through its apps, so using a cookie from an active web session wouldn’t accomplish anything.

Perhaps I’m misunderstanding your suggestion.

**Comment by subdavis** [comment]
No response, closing issue.
