### ISSUE TITLE
New to Github/Python etc.  Authenticated user URL can't be found.

### ISSUE THREAD

**Issue by thew1se** [subdavis/kobo-book-downloader#19]
Hi, Thanks for putting together/continuing this project its just what I need.  I have never done something like this previously so please bear with me as I don't find the instructions complete enough for the layman.

I tried using Python to install kobodl (which seemed to work) because that's what @inhumantsar had in his fork.

Everything seemed to work up to the adding user.  This is also where I fell short using @inhumantsar's version.

I'm trying to download an audiobook.  

Can you point me in the right direction of what I am doing wrong? 

...see attached image where it says: "Authenticated user URL can't be found.  The page format may have changed."

<img width="682" alt="Capture" src="https://user-images.githubusercontent.com/57738712/87715829-ed0a4700-c77b-11ea-8ce1-e634968c6e8a.PNG">

**Comment by thew1se** [comment]
>  branch

**Comment by subdavis** [comment]
From the readme:

> NOTE: You must have a kobo email login for this tool to work (you can't use an external provider like Google or Facebook, or a Walmart login). However, you can create a NEW kobo account and link it with your existing account on the user profile page. Go to My Account -> Account Settings to link your new kobo login.

Are you using a Kobo login?

**Comment by thew1se** [comment]
Yes I have a kobo login.  

On Jul 16, 2020, at 4:16 PM, Brandon Davis <notifications@github.com> wrote:

﻿
From the readme:

NOTE: You must have a kobo email login for this tool to work (you can't use an external provider like Google or Facebook, or a Walmart login). However, you can create a NEW kobo account and link it with your existing account on the user profile page. Go to My Account -> Account Settings to link your new kobo login.

Are you using a Kobo login?

**Comment by subdavis** [comment]
Cannot reproduce.  Really nothing I can do about this.  I've never tested on Windows, but I don't know why that would make a difference.  

I think I'd probably recommend trying to make a new account starting here: https://authorize.kobo.com/us/en/SignUp?returnUrl=https%3a%2f%2fwww.kobo.com%2f%3fnewregister%3dtrue&wslang=en-US

Otherwise, you'll have to dig around in this function.  This regex search is failing: https://github.com/subdavis/kobo-book-downloader/blob/master/kobodl/kobo.py#L458

Sorry.

**Comment by thew1se** [comment]
Ill trying making a new account to see if the account authentication is the problem.

**Comment by subdavis** [comment]
@thew1se I upgraded kobodl to 0.4.0 on pypi.  The new package contains better error reporting for this case.  Please try again.  It should print a message saying that an error file was created.  You'll have to share that error file with me.

Thanks.

**Comment by thew1se** [comment]
Ok. I’m out of town at the moment so haven’t been able to troubleshoot further.  Will try when I return and report.

**Comment by thew1se** [comment]
I tried using a new account, and the old account, using the new version.  Both had the same error - "Authenticated user could not be found."

Error log attached.   One thing to mention, I can't tell if the password is registering properly in my command prompt window. I'm fairly sure it is, as I have tried dummy phrases, however, it would be helpful if it put a character placeholder to visualize that typing the password is getting registered.

Thanks for your help!

![image](https://user-images.githubusercontent.com/57738712/87953782-7e7a0180-ca79-11ea-806c-93d364f882c3.png)

[Error Log.zip](https://github.com/subdavis/kobo-book-downloader/files/4948499/Error.Log.zip)

Thanks for your help!

**Comment by thew1se** [comment]
Just thought I'd mention, I'm not sure I have everything installed on my computer to make this work properly. Do I need anything else other than Python?

**Comment by subdavis** [comment]
From the document you linked

```
<div class="epd-modal show"><div class="validation-summary-errors" data-valmsg-summary="true"><ul><li><p class="title">Account not found</p><span class="content">We didn't find an account with that email address or password. Please check that you've entered them correctly.</span></li>
```


Your login details are incorrect.  try copy-pasting them.

In the mean-time, I'll try to add a better error message to tell the user when their login is wrong.

**Comment by subdavis** [comment]
this could happen if you accidentally added spaces at the beginning or end.

**Comment by thew1se** [comment]
yes tried copy/pasting and typing....both did not work.

**Comment by subdavis** [comment]
There are additional options for providing username and email:

```
kobodl user add --email "email@domain.com" --password "password"
```

Then all you have to paste in is the captcha code.

**Comment by thew1se** [comment]
I have been copy pasting almost every time, but changed to simple password and tried typing again and this time it worked.  I don't know why copy paste didn't work.

**Comment by subdavis** [comment]
Could be some nuance of command-prompt I'm not aware of.  I'll update the docs to mention this option.

**Comment by thew1se** [comment]
My password is usually random generated 20+charaters with symbols/numbers/letters..    Not sure if there is a restriction on password type.

**Comment by subdavis** [comment]
Ooh, I see.  Might be screwing up special characters.

**Comment by thew1se** [comment]
downloaded as expected!  Thanks for your help really appreciate you keeping this live!

**Comment by subdavis** [comment]
I'll investigate the special character issue.  Thanks for following up and helping to debug.

**Comment by thew1se** [comment]
my pleasure.  Could be a copy/paste issue on my end too.  I'm using lastpass password manager and firefox.  Captcha response copy/pasted fine.   Lastpass has a "copy password" button which I then paste into command prompt.  I've never had an issue with it before however.

**Comment by subdavis** [comment]
I changed my password to something with a ton of special characters including quotes and things, and still everything worked fine for me.

Added better logging for the case where username/password is wrong.
