### ISSUE TITLE
"kobodl book list" only lists books marked as "unread"

### ISSUE THREAD

**Issue by hussein-esmail7** [subdavis/kobo-book-downloader#23]
I noticed this when I tried using this (I had 2 unread and 2 finished books, kobodl was only showing the unread books). To solve this I marked the other 2 as unread but you might want to put this in the documentation that the books must be unread or make it so it looks at all titles.

**Comment by naglis** [comment]
I saw there is [`--read` flag](https://github.com/subdavis/kobo-book-downloader/blob/main/kobodl/commands/book.py#L84) to include read titles.

**Comment by subdavis** [comment]
Added another example to the readme.  Thanks.
