### ISSUE TITLE
Try to download audiobook, error : Skipping subscribtion entity

### ISSUE THREAD

**Issue by koenieee** [subdavis/kobo-book-downloader#24]
I get an error when I try to download an audiobook through the kobodl downloader.

The error is: 
Skipping subscribtion entity

I printed the content of the bookMetaData, and the data looks valid. Maybe not yet implemented support for those type of subscriptions? 
Nice project btw!

**Comment by subdavis** [comment]
Try getting the book directly by its identifier.

`kobodl book get <RevisionID>`
