### ISSUE TITLE
Stuck after entering password on 'kobodl user add'

### ISSUE THREAD

**Issue by JSSjogren** [subdavis/kobo-book-downloader#27]
Currently not moving past the point of adding a user in kobodl.

After entering the password for the account in the command 'kobodl user add' the program appears to hang indefinitely.

**Comment by subdavis** [comment]
Just tested version `0.5.0`, cannot reproduce.

> After entering the password for the account in the command 

That's not the last step.   Did you also open a browser and follow the instructions to get a captcha code?

Could you upload a screenshot of what it looks like when it gets stuck?  Could you also include details about your kobodl version and operating system?  Did you install from pypi?

Thanks.

**Comment by subdavis** [comment]
Here's how a login should look.

```bash
brandon@varrock:~
~$ kobodl user add
Email: [REDACTED]         
Password: 
Repeat for confirmation: 

    Open https://authorize.kobo.com/signin in a private/incognito window in your browser, wait till the page
    loads (do not login!) then open the developer tools (use F12 in Firefox/Chrome), select the console tab,
    and paste the following code there and then press Enter there in the browser.

    var newCaptchaDiv = document.createElement( "div" );
    newCaptchaDiv.id = "new-grecaptcha-container";
    document.getElementById( "grecaptcha-container" ).insertAdjacentElement( "afterend", newCaptchaDiv );
    grecaptcha.render( newCaptchaDiv.id, {
        sitekey: "6Le_Hc8ZAAAAAO6IMIG5zdDmANbljtXY4EHK0wzD",
        callback: function( response ) { console.log( "Captcha response:" ); console.log( response ); }
    } );

    A captcha should show up below the Sign-in form. Once you solve the captcha its response will be written
    below the pasted code in the browser's console. Copy the response (the line below "Captcha response:")
    and paste it here.
    
Captcha response: [REDACTED]
Login Success. Try to list your books with `kobodl book list`
```

**Comment by Eng-Ahmd** [comment]
Hi @subdavis 
I am trying to login but I am getting this error

ERROR: Authenticated user URL can't be found. The page format might have changed.

**Comment by subdavis** [comment]
Again, tested 0.5.0, cannot reproduce.  You can send me a copy of the page.  it should be saved to file in the same directory.
