### ISSUE TITLE
Rather minor nit

### ISSUE THREAD

**Issue by DavidNSB** [subdavis/kobo-book-downloader#28]
When I ran python setup.py build, I got an error message:

reading manifest template 'MANIFEST.in'
warning: no directories found matching 'koobdl\commands'
warning: no previously-included files matching '*.pyc' found anywhere in distribution

Looking at manifest.in, I modified the second line from graft koobdl/commands to kobodl/commands.

graft kobodl/templates
graft kobodl/commands
global-exclude *.pyc

**Comment by subdavis** [comment]
Fixed in https://github.com/subdavis/kobo-book-downloader/pull/29

Because that's a package, it gets included in `python setup.py sdist` anyway because of `find_packages()`.  If it had been templates, there would have been an issue!

Thank you.
