### ISSUE TITLE
books missing from list

### ISSUE THREAD

**Issue by EmeraldGreen24** [subdavis/kobo-book-downloader#32]
About half of my Kobo books are missing from the list generated by "kobodl book list" at the command line. I have 237 books including 14 audiobooks in my account, but "kobodl book list" only listed 118 including 3 audiobooks.

I have not been able to see a pattern in the missing ebooks, but I worked out that only in-progress audiobooks appear in the list. Audiobooks marked as unread or finished do not appear in the list. I have confirmed this (and slowly and painfully backed up all my originally missing audiobooks) by downloading the missing audiobooks to my phone and playing a few seconds before running "kobodl book list" again.

**Comment by subdavis** [comment]
Books marked as "read" are hidden by default.

As noted in the [usage documentation](https://github.com/subdavis/kobo-book-downloader#usage) you can show read books with:

```bash
# List all books, including those marked as read
~$ kobodl book list --read
```

Likewise, archived books (found at https://www.kobo.com/us/en/library/archive) are invisible. This is a technical limitation

It's _much_ easier to change books from read to unread or unarchive them through the website.  

If your books are invisible even after passing `--read`, then it will be tricky.  Kobo's API isn't "documented", so this tool represents what I and others have been able to reverse-engineer.  Books that came from promotions, subscriptions, and other non-standard purchases sometimes require different methods of fetching.

If, after using `--read`, you are missing books, all we can really do is form a theory based on a pattern.  Then, I have to buy books matching that pattern and see if they show up. 

Please let me know if this helps.

**Comment by subdavis** [comment]
Update: I added a [troubleshooing section](https://github.com/subdavis/kobo-book-downloader#troubleshooting) to the README to emphasize these points. Hopefully this info is helpful.

**Comment by subdavis** [comment]
No response from reporter.  Closing.
