### ISSUE TITLE
Captcha javascript code not working

### ISSUE THREAD

**Issue by olliums** [subdavis/kobo-book-downloader#36]
When i paste the javascript into the login page to get the captcha code, it shows the captcha but doesn't print the response to the console.

However, you can go into the Network tab, look at the XHR request that's made when you solve the captcha, and get the token from there.

I tried adding an error callback like this:

```js
    grecaptcha.render( newCaptchaDiv.id, {
        sitekey: "6Le_Hc8ZAAAAAO6IMIG5zdDmANbljtXY4EHK0wzD",
        callback: function( response ) { console.log( "Captcha response:" ); console.log( response ); },
        'error-callback': (...args) => console.error(...args)
    } );
```

But neither the callback nor the error-callback gets called.

**Comment by subdavis** [comment]
Cannot reproduce.  You may have made a mistake during copy-paste, or you may have a browser extension interfering somehow.  Please try in an incognito tab with all extensions disabled.

![Screenshot from 2021-03-03 20-49-07](https://user-images.githubusercontent.com/4214172/109898356-17a10580-7c62-11eb-849d-c0ca758c6f17.png)

**Comment by subdavis** [comment]
No response from reporter.
