### ISSUE TITLE
Chapta does not work

### ISSUE THREAD

**Issue by jajpater** [subdavis/kobo-book-downloader#38]
I try to get a chapta code in the way prescribed. But after clicking through the chapta  I get a checkmark in the chaptacheckbox but I don't get a code in the console.

**Comment by subdavis** [comment]
Duplicate of https://github.com/subdavis/kobo-book-downloader/issues/36

Cannot reproduce.  Please try in an incognito browser with all browser extensions disabled.

**Comment by jajpater** [comment]
I did try in incognito browser. I did not disable all browser extensions yet. I will try.

**Comment by subdavis** [comment]
No response from @jajpater, closing.
