### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by vistoh** [subdavis/kobo-book-downloader#39]
Using CMD command console in Windows 10.
After doing the captcha and pasting the captcha response, it says:
"ERROR: Authenticated user URL can't be found. The page format might have changed."

**Comment by subdavis** [comment]
Possible duplicate of https://github.com/subdavis/kobo-book-downloader/issues/37

The error code may be incorrect.  Please follow the instructions in the console when you get this error about looking at the HTML file.

You can look for the text `error-message` and see if there's a message about invalid password or something.  If there isn't please upload the html file in this issue.

**Comment by vistoh** [comment]
My mistake, I wass using "kobo-book-downloader-master" version instead of the "kobo-book-downloader-main" last version.
It works perfectly.
