### ISSUE TITLE
feature request: skip previously downloaded

### ISSUE THREAD

**Issue by victorclaessen** [subdavis/kobo-book-downloader#4]
While testing, I just noticed that when used with `kobodl book get --get-all` it also re-downloads previously downloaded content. Could that be optional? It would be great to just do a --get-all after getting a new book and only download that new one.

**Comment by subdavis** [comment]
Great idea.  I'll try to get to this this weekend.

**Comment by subdavis** [comment]
Released in `0.3.4`, deployed to [docker hub](https://hub.docker.com/layers/subdavis/kobodl/latest/images/sha256-99485933f26aa689122ac1dac77fc4d08ae6549b216c6290984f6cdaafd78134?context=repo)

**Comment by victorclaessen** [comment]
Works for me. Many thanks!
