### ISSUE TITLE
Login html changed, captcha instructions wrong

### ISSUE THREAD

**Issue by MasseR** [subdavis/kobo-book-downloader#40]
While adding a new user, the kobodl requests the user to go to the signin page and run some javascript to render a captcha and return the output. The framework for this works, but some values have changed; grecaptcha-container is not hcaptcha-container and the sitekey is different.

**Comment by subdavis** [comment]
fixed in version 0.6.0

published to pypi, docker image building, main branch is working again.

Thanks.
