### ISSUE TITLE
add new user: the code to cut and paste into console

### ISSUE THREAD

**Issue by helphelpplease** [subdavis/kobo-book-downloader#42]
Hi: where do I get the "code", to cut and paste into the Developer console in Chrome?

"the code" is an image on this github page, so unavailable to cut.  Is it available somewhere I can cut from?

the "code" I am referring to is 
var code captcha div... .. blah blah blah

apologises if I am being super daft.

**Comment by subdavis** [comment]
* It's printed to the console when you run user creation from the command line.
* It's printed to the webpage when you run the tool in web server mode.  The screenshot in the readme is from this page
