### ISSUE TITLE
Long titles problem

### ISSUE THREAD

**Issue by Maverynthia** [subdavis/kobo-book-downloader#43]
Books with multiple volumes that have the same title with "volume x" fail to download and are counted as duplicate if the title is too long. As "FirstAuthor - LastAuthor - This is a really long book name I hope it doesn't get cut off volume 1" Becomes "FirstAuthor - LastAuthor - This is a really long book name I hope it" and thus volume 2 has the same name as volume 1 as the "volume X" is cut off.

Possible fix is to ask user input if duplicate title is found to manually name the file Vol 1 or vol 2 or such?

**Comment by subdavis** [comment]
Fixed in 0.7.0 release
