### ISSUE TITLE
Install appears not to have worked

### ISSUE THREAD

**Issue by helphelpplease** [subdavis/kobo-book-downloader#45]
Hi: i think the problem could be install has not worked.
Catalina 10.15

1 In terminal navigated to directory where  I want the kobo down loader to be
tried:
bash-3.2$ ~$ kobodl user add
bash: ~$: command not found
bash-3.2$ 

tried:
bash: ~$: command not found
bash-3.2$ kobodl user add
bash: kobodl: command not found
bash-3.2$ 

Install:
1) in terminal, navigated to directory where I want the downloader to be
/macKOBO
2) in terminal typed  pip3 install kobodl
installed successfully

**Comment by subdavis** [comment]
User error, your PATH is probably configured improperly.  Fix PATH or use a virtual environment like https://docs.python.org/3/tutorial/venv.html

There's nothing wrong kobodl.
