### ISSUE TITLE
Feature Request: --get-all supports --read

### ISSUE THREAD

**Issue by NomadThanatos** [subdavis/kobo-book-downloader#54]
Since I manage my books by subdirectories, the feature gh-4 does not work well in that situation.

I use read flag to mark those downloaded.

My workaround here:
```
kobodl book list | tail -n +3 | awk -F '  ' '{print $3}' | xargs kobodl book get --format-str '{Title}'
```

**Comment by subdavis** [comment]
I looked into it and this is tricky because listing to list and listing to download function differently.  I don't plan on spending time to do this.  Looks like your workaround is reasonable.
