### ISSUE TITLE
Failed to verify kobodl version (pip3 install on macbook)

### ISSUE THREAD

**Issue by stillhope** [subdavis/kobo-book-downloader#57]
I am not very technical and fill I must be doing something very stupid. Apologises ahead of time

**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl)
step 1 verified I have python3 installed on Catalina macbook
step 2 Installation: downloaded latest release of the Pre-built bundle for Catalina macbook provided
step 1, in terminal
wget https://github.com/subdavis/kobo-book-downloader/releases/latest/download/kobodl-macos-latest
step 2 rename file "kobodl-macos-latest" to "kobodl"
step 3 in terminal navigate to directory where kobodl is located.
step 4 in terminal write pip3 install kobodl

Terminal message:
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kobodl in /Users/xxx/Library/Python/3.8/lib/python/site-packages (0.6.0

**Describe the issue**
I failed to verify the kobodl version using the command. So I am not confident I have kobodl installed correctly. 

Instructions (https://github.com/subdavis/kobo-book-downloader) say:
get version
~$ kobodl --version

I dont know what ~$  means. i know ~ at front of folder means hidden folder.  I thought $ means my home directory.  But what is ~$ ?

**To Reproduce**
1. Installed latest mac version as above 4 steps
2. In terminal write kobodl --version
3. see error "command not found"

bash-3.2$ kobodl --version
bash: kobodl: command not found
bash-3.2$ ~$ kobodl --version
bash: ~$: command not found
bash-3.2$ python3 kobodl --version
  File "kobodl", line 1
SyntaxError: Non-UTF-8 code starting with '\xcf' in file kobodl on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
bash-3.2$ python3 ~$ kobodl --version
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '~$': [Errno 2] No such file or directory
bash-3.2$ 

I clearly have no idea about this stuff. I try...

4 checked the python3 site packages directory /Users/xx/Library/Python/3.8/lib/python/site-packages
Verified 2 folders
kobodl
kobodl-0.6.0.dist-info

**Expected behavior**
I was expecting to see the kobodl version, 0.7.3 as per page https://pypi.org/project/kobodl/#files. I feel super stupid. Apologises.

**Desktop (please complete the following information):**
 - OS: [10.15.6]
-  Install: pip3, python 3.8 when I do python --version python 2.7 returns. I installed python 3.8 a year back.
 - Kobodl Version [e.g. not sure trying to see ]

Question 2 I am trying to understand the tool.  Does this tool allow me to input deviceID or ClientKey from my Android device where the Kobo Android App is running, and my purchased books are?  Or does it ignore all this setup completely and creates a new Android device on my macbook. 

I looked in kobo.py and could see
    Affiliate = "Kobo"
    ApplicationVersion = "8.11.24971"
    DefaultPlatformId = "00000000-0000-0000-0000-000000004000"
    DisplayProfile = "Android"

My android kobo app shows
https://storeapi.kobo.com/v1/auth/device
{
	"AffiliateName": "Kobo",
	"AppVersion": "7.2.21851",
	"ClientKey": "MDAwREDACTED remaining",
	"DeviceId": "543R REDACTED remaining",
	"PlatformId": "00000000-0000-0000-0000-000000004000”
}

Thankyou so much for any assistance. Apologises that my question is very likely stupid.
sorry I dont know how my issue was logged as a bug on github, rather than an issue/question

**Comment by subdavis** [comment]
You've mixed install methods.  If you download the bundle, you don't need python.

Just download `kobodl-macos-latest` and then run it.

```
chmod +x kobodl-macos-latest
./kobodl-macos-latest --version
```

**Comment by stillhope** [comment]
Thankyou. Still have error

kobodl-macos-latest 100%[===================>]   9.05M   927KB/s    in 12s     

2021-11-04 09:31:37 (744 KB/s) - ‘kobodl-macos-latest’ saved [9494960/9494960]

bash-3.2$ chmod +x kobodl-macos-latest
bash-3.2$ ./kobodl-macos-latest --version
Traceback (most recent call last):
  File "kobodl/main.py", line 5, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 781, in main
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1212, in parse_args
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "click/decorators.py", line 295, in callback
RuntimeError: Could not determine version
[2051] Failed to execute script 'main' due to unhandled exception!
bash-3.2$

**Comment by subdavis** [comment]
Forgot that the prebuilt binary doesn't have a version.  You can still do everything else with it though

```
./kobodl-macos-latest --help
./kobodl-macos-latest user --help
```

**Comment by stillhope** [comment]
thankyou
