### ISSUE TITLE
Failed adding user: Captcha: after entering captcha response + click enter, nothing happens in terminal

### ISSUE THREAD

**Issue by stillhope** [subdavis/kobo-book-downloader#58]
Install using binary bundle (kobodl-macos-latest)

**Describe the issue**
Failed adding new user.   
./kobodl-macos-latest user add

**To Reproduce**
1. Navigated to directory where kobodl-macos-latest is located in terminal
2. In terminal, typed ./kobodl-macos-latest user add
3. Entered my kobo login email on prompt
4. Entered my kobo passcode on prompt
5. Opened chrome incognito window, opened developer mode, click Console Tab
6. Cut and pasted code into Console tab as per instructions
7. clicked the check box
8. cut the captcha response
9. pasted the captcha response in terminal
10. clicked enter

Nothing happens.
repeated three times now. 
Checked no user added as suspected, typing in terminal ./kobodl-macos-latest user list
Email    UserKey    DeviceId
-------  ---------  ----------
xx@xx-MacBook-Air mackobo % 

**Expected behavior**
A new user to be added to kobodl

<img width="415" alt="new user kobodl" src="https://user-images.githubusercontent.com/85041592/140194453-25b97a95-78ef-45e2-bd06-c871d5f9e154.png">

**Desktop (please complete the following information):**
 - OS: [10.15.6]
-  binary bundle for mac, python 3.8
 - Kobodl Version [assuming latest]

Thankyou for any assistance.

**Comment by subdavis** [comment]
Try not pasting it. The captcha response should be read from your clipboard without having to paste.  The "paste it here" instruction is outdated.

Just copy it, come back, and press enter.

**Comment by stillhope** [comment]
Thankyou, that worked.
Do I need to only do the captcha hack, each time I login to kobodl or once in for period of time?
Does kobodl support being on a VPN ?

**Comment by subdavis** [comment]
You only have to log in once.  You shoudln't need to do that again.

If you have a VPN active, all connections, including Kobodl, will use it.
