### ISSUE TITLE
10.13 supported for kobodl?

### ISSUE THREAD

**Issue by helphelpplease** [subdavis/kobo-book-downloader#59]
Does kobodl work with high Sierra 10.13.6? Python3.7

**To Reproduce**
1. Installed kobodl using bundle to Mac, in terminal
wget https://github.com/subdavis/kobo-book-downloader/releases/latest/download/kobodl-macos-latest
chmod +x kobodl-macos-latest
All looked ok, no errors

2. Check if installed ok , in terminal
./kobodl-macos-latest user --help

Macintosh:kobodl MENA$ ./kobodl-macos-latest user --help
[2251] Error loading Python lib '/var/folders/x4/wyjknyfx731_tl1t7g8wcnt40000gn/T/_MEIFZMs8j/libpython3.8.dylib': dlopen: dlopen(/var/folders/x4/wyjknyfx731_tl1t7g8wcnt40000gn/T/_MEIFZMs8j/libpython3.8.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /var/folders/x4/wyjknyfx731_tl1t7g8wcnt40000gn/T/_MEIFZMs8j/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/x4/wyjknyfx731_tl1t7g8wcnt40000gn/T/_MEIFZMs8j/libintl.8.dylib

5 checked python folder (library/Python). 2.7 and 3.7 folders are there
6 Installed python 3.9 after getting error, first time.
Redid installation and same error results.

**Expected behavior**
Kobodl working on high Sierra 10.13

**Desktop (please complete the following information):**
 - OS: [e.g. 10.13.6]
-  bundle latest for Mac, python 3.7 
 - Kobodl Version [e.g. 0.6.0]

**Additional context**

cheers

**Comment by subdavis** [comment]
Apparently Kobodl was built on a version of MacOS that is too new and therefore doesn't work on 10.13

https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible

I'll see if I can build it on an older version.

**Comment by helphelpplease** [comment]
Thankyou. That would be greatly appreciated.

**Comment by subdavis** [comment]
I've looked and it will not be possible to build for anything older than catalina because github only has runners for catalina and big sur.  I'll update the documentation saying that MacOS Catalina (10.15) or newer is required.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by subdavis** [comment]
You can easily use kobodl by using a different install method, such as with pip.

`pip install kobodl`

**Comment by helphelpplease** [comment]
Ok. Thankyou for trying.
