### ISSUE TITLE
Problem downloading an audiobook

### ISSUE THREAD

**Issue by bybpow** [subdavis/kobo-book-downloader#62]
Hi:

I'm having some trouble downloading a single audiobook. All others work fine. The audiobook is "Lord Foul’s Bane". Although I'm not good in Python I've tried to do some debugging and it seems that specific abook is returning a Size of 0. The app download the files but they are empty-corrupted.
Any clue why this happens? I'll try to do some more debugging tomorrow.

Thanks in advance.

**Comment by subdavis** [comment]
Is there anything special about this book?  The way you bought it?  Was it free, purchased for points?  From a subscription that ended? 

if it's just that one, there's nothing I can do to debug it.  If you figure it out, let me know.

**Comment by bybpow** [comment]
No, purchased as always. In data abook is active etc. I think I've found the problem. In the book metadata there is no filesize meanwhile in other books there is. That's making it fail. You can check it for example going to last part of the page in details:
https://www.kobo.com/es/es/audiobook/lord-foul-s-bane-3
In any other book the size is there. Is there anyway I can know what that filesize and add it manually?

**Comment by bybpow** [comment]
I already got the filesize: it should be 538mb. I'll try to implement it manually somehow but I doubt I can manage to make it work with my current knowledge.

**Comment by subdavis** [comment]
I just published version 0.8.0 which includes a new `--debug` option, for example `kobodl --debug book get <id>`

If you update to the new version, this will generate a `debug.log` file which you could email me if you'd like more help.

**Comment by subdavis** [comment]
More docs here: https://github.com/subdavis/kobo-book-downloader/releases/tag/0.8.0

**Comment by bybpow** [comment]
Thank you reallt much for this. I was using prints for debbugind until xd. The book is now down:
https://www.kobo.com/es/es/audiobook/lord-foul-s-bane-3
Once is back online I'll try it asap. Again, thanks for the update.

**Comment by subdavis** [comment]
Closing this as a stale issue.  Feel free to reopen if any new information comes up.
