### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by irisvdz83** [subdavis/kobo-book-downloader#63]
I tried to use your fork today, got as far as entering the captcha response, then it tells me this:

ERROR: Can't find the workflow ID in the login form. The page format might have changed.

I saw this issue being reported in the original fork as well, not sure what I could to to fix this? 

**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl)

**Describe the issue**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  MacOS]
-  Install method and python version: [eg. docker, python 3.9]
 - Kobodl Version [e.g. 0.6.0]

**Additional context**

**Comment by irisvdz83** [comment]
Ok srry just discovered the new way of working... i have a 3rd party kobo account thats probably the issue... trying again tomorrow...

**Comment by subdavis** [comment]
Closing for now, please open a new issue if you have a different issue.  Thansk.
