### ISSUE TITLE
Captcha trouble

### ISSUE THREAD

**Issue by tamaracks** [subdavis/kobo-book-downloader#73]
I can't get the captcha steps to give me a code. After entering the javascript code in the console and hitting enter, it says undefined under the code. The page changes to only show the captcha area and nothing else. And when I check the box in the captcha, the console shows "Captcha response:" but it's blank after.

I just installed kobold, and I do have a regular Kobo books account.

**Before you open an issue**
Please make sure you've upgraded to the latest version of kobodl on [pypi](https://pypi.org/project/kobodl/) or [docker](https://hub.docker.com/r/subdavis/kobodl).  Also read through the [troubleshooting guide](https://github.com/subdavis/kobo-book-downloader#troubleshooting).

**Describe the issue**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  MacOS]
-  Install method and python version: [eg. docker, python 3.9]
 - Kobodl Version [e.g. 0.6.0]

**Additional context**

**Comment by bybpow** [comment]
The problem happens to you in the browser or in the terminal?

**Comment by tamaracks** [comment]
In the browser. I don't have anything to copy to paste in the terminal, so I don't get that far.

I meant to upload a screenshot of the console, so I'll attach that now.

<img width="1340" alt="Screen Shot 2022-01-16 at 12 34 30 AM" src="https://user-images.githubusercontent.com/1423990/149648906-c20192e5-1900-46de-b3e7-340143bb54e5.png">

**Comment by bybpow** [comment]
Can you please copy-paste the code so I can test it?

**Comment by bybpow** [comment]
It works for me.
![Capture](https://user-images.githubusercontent.com/62562341/149649015-7147315c-f50c-4869-a4e7-d84b1c155b53.PNG)

What browser are you using?

**Comment by tamaracks** [comment]
var newCaptchaDiv = document.createElement("div");
newCaptchaDiv.id = "new-hcaptcha-container";
var siteKey = document.getElementById('hcaptcha-container')
  .getAttribute('data-sitekey');
document.body.replaceChildren(newCaptchaDiv);
grecaptcha.render( newCaptchaDiv.id, {
    sitekey: siteKey,
    callback: function(r) {
      console.log("Captcha response:");
      console.log(r);
    }
});
console.log('Click the checkbox to get the code');

**Comment by tamaracks** [comment]
I'm using Chrome. On macOS monterey.

**Comment by tamaracks** [comment]
I don't know why my console doesn't show the 'Click the checkbox to get the code' line, even though it's in the code I pasted.

**Comment by bybpow** [comment]
It's weird. I'm in PC so maybe I can't reproduce the error. Can you go to this URL:
https://authorize.kobo.com/signin
and do the same?

**Comment by tamaracks** [comment]
Sigh. I just realized the problem. I had filtered the console while trying to figure something out, and it was still filtered. So it was working, but I wasn't seeing the response. 

So sorry about that. Thanks for your help!

**Comment by bybpow** [comment]
Happy to know you solved it. No problem!
