### ISSUE TITLE
[Critical bug] kobodl gets stuck during authentication and fetching books

### ISSUE THREAD

**Issue by steed12** [subdavis/kobo-book-downloader#76]
### Discussed in https://github.com/subdavis/kobo-book-downloader/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **steed12** February 17, 2022</sup>
Hi,
I installed, configured and used kobodl last week. From yesterdady i am trying to download my entire library again but the script still after the "kobodl book get --get-all". Also with the command for the list, no answer.
With "kobodl user list" i can get my account. So i tried to remove my account and to re add it. All seem to go straight until i enter the captcha code: no answer.
What can be the problem?

Thank you for the answer and the work.</div>

**Comment by Nosgoroth** [comment]
Same here. I've just tracked it down to the call to `https://storeapi.kobo.com/v1/initialization` in `kobo.LoadInitializationSettings()` but I can't tell why.

**Comment by leavion** [comment]
Same here. It worked until couple of days ago. Is it possible the Kobo is blocking access?

**Comment by subdavis** [comment]
There is a partial fix working on branch "authfix" -- https://github.com/subdavis/kobo-book-downloader/tree/authfix

This will let you download books again IF you've already authenticated a user with kobodl (and you know how to run the tool from source code).

There's a tougher problem with authentication of new users.  You'll still get stuck at the captcha, and I will need to work on it more.  It's not likely that I'll resolve this soon.

Meanwhile, you can also see https://github.com/subdavis/kobo-book-downloader#alternatives-to-kobodl for a way to get your books using a calibre plugin

**Comment by steed12** [comment]
news? Thank you

**Comment by subdavis** [comment]
Unlikely that this will work again.  I tend to drop maintenance on software that I don't use anymore, and I've moved entirely to Calibre + the two plugins listed at the top of the readme.

I do kinda want to fix this just because I don't want to let Kobo.com win, but more than likely I'm just not going to get around to it.  If anyone with reverse engineering skills can fix the authorization flow, I'll happily accept a PR.

I recommend switching to https://github.com/Leseratte10/acsm-calibre-plugin and/or DeDRM tools for all your Kobo needs. 

It was fun while it lasted.

**Comment by Nosgoroth** [comment]
I tried to mitmproxy the Kobo app in an Android emulator, but I'm hardly an expert in this and the cert pinning got me.

I don't use Calibre for library management, so this code is much more useful for me than the suggested alternate flow. I might bash my head against this one more time at some point, but I can't promise any results.

**Comment by steed12** [comment]
@Nosgoroth tell me if you need help.

**Comment by TnS-hun** [comment]
See [this](https://github.com/TnS-hun/kobo-book-downloader/commit/895d2a2cb5c1f4b10cf5cc282c6008c9ecc5e504) commit for how to support hCaptcha.

**Comment by Nosgoroth** [comment]
> See [this](https://github.com/TnS-hun/kobo-book-downloader/commit/895d2a2cb5c1f4b10cf5cc282c6008c9ecc5e504) commit for how to support hCaptcha.

Thank you so much! I got it working.

@subdavis I'll try to figure out how to make a PR (never made one)

**Comment by subdavis** [comment]
0.9.0 released to pypi, thanks everyone.
