### ISSUE TITLE
Error: 403 Client Error.  Authorization flow is broken.

### ISSUE THREAD

**Issue by tioui** [subdavis/kobo-book-downloader#80]
Hi, I try to connect the kobodl to Kobo API using the new Capcha mecanism. It seems to found everything it need to connect, but when actually opening the API, it receive a 403 Client Error. I have attached the log file (without my credential of course).

[kobo_error.log](https://github.com/subdavis/kobo-book-downloader/files/8533257/kobo_error.log)

Desktop:
 - OS: Linux Ubuntu 20.04
 - Install method: git clone
 - python version: Python 3.8.10
 - Kobodl Version: kobodl, version 0.9.0

**Comment by subdavis** [comment]
Yes, as you've noticed, Kobo has broken authentication again.

This is related to https://github.com/TnS-hun/kobo-book-downloader/issues/19

I spent some time trying to figure this out yesterday but I was unsuccessful.  Adding some headers (`Origin`, `Referrer`, `Host`) to the auth request got me from 403 to "request hangs forever" so there's clearly something there.

**Comment by tioui** [comment]
And I presume that it is not possible to see what headers the Kobo Android App is using? It is probably encrypted.

**Comment by subdavis** [comment]
# Workaround

For now, this tool is again broken.  See the aternatives at the top of the readme for a different, better way to get your books. 
 
https://github.com/subdavis/kobo-book-downloader#alternatives-to-kobodl=

**Comment by TnS-hun** [comment]
[This](https://github.com/TnS-hun/kobo-book-downloader/commit/fe3e740e8bf1f04103785eae07d9d22469760795) change has fixed the issue for me.

**Comment by tioui** [comment]
The fix worked. I created a Pull request for the fix.

**Comment by tioui** [comment]
> # Workaround
> 
> For now, this tool is again broken. See the aternatives at the top of the readme for a different, better way to get your books.
> 
> https://github.com/subdavis/kobo-book-downloader#alternatives-to-kobodl=

Not usable for me because I only have audiobooks on my Kobo account.

**Comment by subdavis** [comment]
Fixed in #81
