### ISSUE TITLE
Bol.com support

### ISSUE THREAD

**Issue by TheSupraLife** [subdavis/kobo-book-downloader#84]
Is there a way to sign in with a bol.com account?

**Comment by subdavis** [comment]
No.  Please see the readme:

NOTE: You must have a kobo email login for this tool to work (you can't use an external provider like Google or Facebook). However, you can create a NEW kobo account and link it with your existing account on the user profile page. Go to My Account -> Account Settings to link your new kobo login.

**Comment by chewi** [comment]
Mine hangs even though I think I do have the right kind of account.

![image](https://user-images.githubusercontent.com/35072/169716455-eb3b13ac-a61b-4418-9819-8042291e85fa.png)

I wasn't sure if a Rakuten ID was the same thing, so I tried creating a new Kobo account. With the same address, it said it was already taken. With a different address, it said I can't link two accounts of the same type. :confused:
