### ISSUE TITLE
captcha response is 3143 characters long and cannot be pasted entirely

### ISSUE THREAD

**Issue by gdemontalivet** [subdavis/kobo-book-downloader#92]
Hi, I tried this today but the captain response is much longer than on your small video, it doesn't seem to work anymore as when pasting it in command line, it doesn't paste more than the  1024 first chatacters

**Comment by subdavis** [comment]
Thanks for the report.

Kobodl is fragile.  If you're trying to get an ebook, I recommend reading https://github.com/subdavis/kobo-book-downloader#alternatives-to-kobodl (the alternative method).

**Comment by gdemontalivet** [comment]
the issue was solved on tons-hun version, anyway you could modify it also on your side? https://github.com/TnS-hun/kobo-book-downloader/commit/3f365f8d3c51fd2c458b496a4c8d0783767a2ab1

**Comment by subdavis** [comment]
I've looked into this issue, and this version was not affected by the bug in TnS-hun's version.   It uses pyperclip to read the clipboard, not `input()`.  Confirmed authorization is still working on macos today.
