### ISSUE TITLE
Login not possible using docker image on Arch Linux

### ISSUE THREAD

**Issue by relthyg** [subdavis/kobo-book-downloader#97]
**Describe the issue**
After pasting the captcha response I get a

```
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
```

**To Reproduce**
1. Run `docker run --rm -it --user $(id -u):$(id -g)   -v ${HOME}/.config:/home/config   ghcr.io/subdavis/kobodl   --config /home/config/kobodl.json user add`
2. Enter your Kobo credentials (Why do I have to enter my password twice??)
3. Open https://authorize.kobo.com/signin in your Browser
4. Copy the JavaScript code to your browsers's console and execute it
5. Solve the captcha
6. Copy the captcha response and paste it into your terminal window

**Expected behavior**
I should be logged in

**Desktop (please complete the following information):**
 - OS: [Arch Linux]
-  Install method and python version: docker
 - Kobodl Version: No idea, i just ran the docker command above

**Comment by subdavis** [comment]
@relthyg thanks, added a workaround in #99
